### ISSUE TITLE
impossible to install in python 3.7.9

### ISSUE THREAD

**Issue by doubianimehdi** [stephenleo/stripnet#6]
Hi,

I can't install the package because of numpy ...
Collecting stripnet
  Downloading stripnet-0.0.5-py3-none-any.whl (11 kB)
  Downloading stripnet-0.0.4-py3-none-any.whl (11 kB)
  Downloading stripnet-0.0.3-py3-none-any.whl (11 kB)

The conflict is caused by:
    stripnet 0.0.6 depends on numpy==1.22.0
    stripnet 0.0.5 depends on numpy==1.22.0
    stripnet 0.0.4 depends on numpy==1.22.0
    stripnet 0.0.3 depends on numpy==1.22.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

I have a virtual pipenv environnement in python 3.7.9

**Comment by stephenleo** [comment]
Unfortunately the `numpy` restriction was to solve an ongoing issue with HDBSCAN which is required by BERTopic: https://github.com/scikit-learn-contrib/hdbscan/issues/457. So until HDBSCAN releases a new version we're stuck with it

You're unable to install numpy 1.22 because of python 3.7? Can I check if it works while using python 3.8 instead?

**Comment by doubianimehdi** [comment]
Yes it works with Python 3.8 only ...

**Comment by stephenleo** [comment]
Thanks for confirming. Unfortunately until HDBSCAN releases a new version with the fix I think we're stuck with this :( I'll update setup.py to mention only python 3.8.

If ok, I'll close this ticket with that change
